theme = "zen"
baseURL = "https://outerheavenproject.github.io/"
title = "outer-heaven.fm"
languageCode = "ja-jp"
publishDir = "public"
assetDir = "static"

[author]
name = "OUTER HEAVEN PROJECT"
url = "https://github.com/outerheavenproject"

[params]
logo = false
feedlinks = true
footer = """
[<img src='/google_podcasts_badge.svg' width='134' height='34' />](https://www.google.com/podcasts?feed=aHR0cHM6Ly9vdXRlcmhlYXZlbnByb2plY3QuZ2l0aHViLmlvL3BvZGNhc3QvaW5kZXgueG1s)
"""

[params.podcast]
title = "outer-heaven.fm"
description = "Android を中心として Native アプリ界隈を取り巻く技術や、組織、環境の話をざっくばらんに話す OUTER HEAVEN PROJECT の Podcast"
author = "OUTER HEAVEN PROJECT"
image = "images/ohfm.png"

[params.podcast.owner]
name = "OUTER HEAVEN PROJECT"
email = "outer-heaven-project@googlegroups.com"

[params.podcast.category]
name = "Technology"

[markup.goldmark.renderer]
unsafe = true
