theme = "zen"
baseURL = "https://outerheavenproject.github.io/podcast/"
title = "outer-heaven.fm"
languageCode = "ja-jp"
publishDir = "docs"

[author]
name = "OUTER HEAVEN PROJECT"
url = "https://github.com/outerheavenproject"

[params]
logo = false

[markup.goldmark.renderer]
unsafe = true
