theme = "zen"
baseURL = "https://outerheavenproject.github.io/"
title = "outer-heaven.fm"
languageCode = "ja-jp"
publishDir = "public"

[author]
name = "OUTER HEAVEN PROJECT"
url = "https://github.com/outerheavenproject"

[params]
logo = false

[params.podcast]
title = "outer-heaven.fm"
description = "Android を中心として Native アプリ界隈を取り巻く技術や、組織、環境の話をざっくばらんに話す OUTER HEAVEN PROJECT の Podcast"
author = "OUTER HEAVEN PROJECT"

[params.podcast.category]
name = "Technology"

[markup.goldmark.renderer]
unsafe = true
